# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Making It - From Self-Taught to Aspiring Front-End Developer
email: jruzsilla@gmail.com
description: A blog about my journey to becoming a front-end developer
baseurl: '/makingIt'
url: "http://makingit.me" # the base hostname & protocol for your site
twitter_username: jr_code03
github_username:  jruz10
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title